services:
  - type: web
    name: zebvo-scraper-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://rajat420:rajat420@cluster0.e6fwwx1.mongodb.net/zebvo_scraper?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: super_secret_jwt_key_2026_zebvo
      - key: SCRAPE_INTERVAL_MINUTES
        value: 15
